import line241 from "@/assets/images/line241.jpg";
import line241Back from "@/assets/images/line241-back.png";

export const pokemons = [
  {
    id: 0,
    name: "kav 241",
    types: ["Normal"],
    height: 1.78,
    weight: 15,
    frontViewImageUrl: line241.src,
    backViewImageUrl: line241.src,
    frontShinyViewImageUrl: line241Back.src,
    backShinyViewImageUrl: line241Back.src,
  },
  {
    id: 0,
    name: "kav 241",
    types: ["Normal"],
    height: 1.78,
    weight: 15,
    frontViewImageUrl: line241.src,
    backViewImageUrl: line241.src,
    frontShinyViewImageUrl: line241Back.src,
    backShinyViewImageUrl: line241Back.src,
  },
  {
    id: 0,
    name: "kav 241",
    types: ["Normal"],
    height: 1.78,
    weight: 15,
    frontViewImageUrl: line241.src,
    backViewImageUrl: line241.src,
    frontShinyViewImageUrl: line241Back.src,
    backShinyViewImageUrl: line241Back.src,
  },
  {
    id: 0,
    name: "kav 241",
    types: ["Normal"],
    height: 1.78,
    weight: 15,
    frontViewImageUrl: line241.src,
    backViewImageUrl: line241.src,
    frontShinyViewImageUrl: line241Back.src,
    backShinyViewImageUrl: line241Back.src,
  },
  {
    id: 0,
    name: "kav 241",
    types: ["Normal"],
    height: 1.78,
    weight: 15,
    frontViewImageUrl: line241.src,
    backViewImageUrl: line241.src,
    frontShinyViewImageUrl: line241Back.src,
    backShinyViewImageUrl: line241Back.src,
  },
  {
    id: 0,
    name: "kav 241",
    types: ["Normal"],
    height: 1.78,
    weight: 15,
    frontViewImageUrl: line241.src,
    backViewImageUrl: line241.src,
    frontShinyViewImageUrl: line241Back.src,
    backShinyViewImageUrl: line241Back.src,
  },
  {
    id: 0,
    name: "kav 241",
    types: ["Normal"],
    height: 1.78,
    weight: 15,
    frontViewImageUrl: line241.src,
    backViewImageUrl: line241.src,
    frontShinyViewImageUrl: line241Back.src,
    backShinyViewImageUrl: line241Back.src,
  },
  {
    id: 0,
    name: "kav 241",
    types: ["Normal"],
    height: 1.78,
    weight: 15,
    frontViewImageUrl: line241.src,
    backViewImageUrl: line241.src,
    frontShinyViewImageUrl: line241Back.src,
    backShinyViewImageUrl: line241Back.src,
  },
  {
    id: 0,
    name: "kav 241",
    types: ["Normal"],
    height: 1.78,
    weight: 15,
    frontViewImageUrl: line241.src,
    backViewImageUrl: line241.src,
    frontShinyViewImageUrl: line241Back.src,
    backShinyViewImageUrl: line241Back.src,
  },
  {
    id: 0,
    name: "kav 241",
    types: ["Normal"],
    height: 1.78,
    weight: 15,
    frontViewImageUrl: line241.src,
    backViewImageUrl: line241.src,
    frontShinyViewImageUrl: line241Back.src,
    backShinyViewImageUrl: line241Back.src,
  },
  {
    id: 0,
    name: "kav 241",
    types: ["Normal"],
    height: 1.78,
    weight: 15,
    frontViewImageUrl: line241.src,
    backViewImageUrl: line241.src,
    frontShinyViewImageUrl: line241Back.src,
    backShinyViewImageUrl: line241Back.src,
  },
  {
    id: 0,
    name: "kav 241",
    types: ["Normal"],
    height: 1.78,
    weight: 15,
    frontViewImageUrl: line241.src,
    backViewImageUrl: line241.src,
    frontShinyViewImageUrl: line241Back.src,
    backShinyViewImageUrl: line241Back.src,
  },
  {
    id: 0,
    name: "kav 241",
    types: ["Normal"],
    height: 1.78,
    weight: 15,
    frontViewImageUrl: line241.src,
    backViewImageUrl: line241.src,
    frontShinyViewImageUrl: line241Back.src,
    backShinyViewImageUrl: line241Back.src,
  },
  {
    id: 0,
    name: "kav 241",
    types: ["Normal"],
    height: 1.78,
    weight: 15,
    frontViewImageUrl: line241.src,
    backViewImageUrl: line241.src,
    frontShinyViewImageUrl: line241Back.src,
    backShinyViewImageUrl: line241Back.src,
  },
  {
    id: 0,
    name: "kav 241",
    types: ["Normal"],
    height: 1.78,
    weight: 1,
    frontViewImageUrl: line241.src,
    backViewImageUrl: line241.src,
    frontShinyViewImageUrl: line241Back.src,
    backShinyViewImageUrl: line241Back.src,
  },
  {
    id: -1,
    name: "kav 241",
    types: ["Normal"],
    height: 1.28,
    weight: 15,
    frontViewImageUrl: line241.src,
    backViewImageUrl: line241.src,
    frontShinyViewImageUrl: line241Back.src,
    backShinyViewImageUrl: line241Back.src,
  },
  {
    id: 54,
    name: "kav 241",
    types: ["Normal"],
    height: 1.78,
    weight: 15,
    frontViewImageUrl: line241.src,
    backViewImageUrl: line241.src,
    frontShinyViewImageUrl: line241Back.src,
    backShinyViewImageUrl: line241Back.src,
  },
  {
    id: 0,
    name: "kav 241",
    types: ["Normal"],
    height: 1.78,
    weight: 15,
    frontViewImageUrl: line241.src,
    backViewImageUrl: line241.src,
    frontShinyViewImageUrl: line241Back.src,
    backShinyViewImageUrl: line241Back.src,
  },
  {
    id: 0,
    name: "bbbbkav 241",
    types: ["Normal"],
    height: 1.78,
    weight: 15,
    frontViewImageUrl: line241.src,
    backViewImageUrl: line241.src,
    frontShinyViewImageUrl: line241Back.src,
    backShinyViewImageUrl: line241Back.src,
  },
  {
    id: 0,
    name: "kav 241",
    types: ["Normal"],
    height: 1.78,
    weight: 15,
    frontViewImageUrl: line241.src,
    backViewImageUrl: line241.src,
    frontShinyViewImageUrl: line241Back.src,
    backShinyViewImageUrl: line241Back.src,
  },
  {
    id: 0,
    name: "aaakav 241",
    types: ["Normal"],
    height: 1.78,
    weight: 15,
    frontViewImageUrl: line241.src,
    backViewImageUrl: line241.src,
    frontShinyViewImageUrl: line241Back.src,
    backShinyViewImageUrl: line241Back.src,
  },
];
